### ISSUE TITLE
rxn class graphs "unclassified" vs previous classification as H migration or substitution

### ISSUE THREAD

**Issue by lpratalimaffei** [Auto-Mech/mechanalyzer#294]
@avcopan @snelliott  when re-testing mechanalyzer I found three cases of sorting of reactions by class (from reaction line only, so let's say from the InChIs) that stopped working. In the test, I commented the line that I got previously. these are the three cases

https://github.com/Auto-Mech/mechanalyzer/blob/777991b8330d0e85bd544b9cec55b75949f6d192/mechanalyzer/tests/test__sorter.py#L301

https://github.com/Auto-Mech/mechanalyzer/blob/777991b8330d0e85bd544b9cec55b75949f6d192/mechanalyzer/tests/test__sorter.py#L304

https://github.com/Auto-Mech/mechanalyzer/blob/777991b8330d0e85bd544b9cec55b75949f6d192/mechanalyzer/tests/test__sorter.py#L307

here is where I call the reaction classifier within the sorter:
https://github.com/Auto-Mech/mechanalyzer/blob/777991b8330d0e85bd544b9cec55b75949f6d192/mechanalyzer/builder/rxnclass.py#L261

could you give a look at this to make sure this is not an error? I would expect the H migration to work at least. the substitution is probably more debatable. thanks!

**Comment by avcopan** [comment]
@lpratalimaffei I am testing these and the first one seems to be correctly recognized by AutoMol:
```
>>> import automol
>>> rxn, *_ = automol.reac.from_smiles(["[CH2]C=C"], ["[CH]=CC"], stereo=False)
>>> automol.reac.display(rxn)
```
![Screenshot 2024-08-20 095413](https://github.com/user-attachments/assets/deab4d21-6623-4583-9395-a2e9f11fe8e4)
```
>>> print(automol.reac.class_(rxn))
hydrogen migration
```

**Comment by avcopan** [comment]
I will try testing it directly as in the link you sent...

**Comment by avcopan** [comment]
The hydrogen migration seems to work when called directly through mechanalyzer as well:
```
>>> import mechanalyzer.builder.rxnclass
>>> 
>>> spc_dct = {'C3H5-A': {'inchi': 'InChI=1S/C3H5/c1-3-2/h3H,1-2H2', 'fml': {'C': 3, 'H': 5}},
>>>            'C3H5-S': {'inchi': 'InChI=1S/C3H5/c1-3-2/h1,3H,2H3', 'fml': {'C': 3, 'H': 5}}}
>>> mechanalyzer.builder.rxnclass.classify_graph(spc_dct, ('C3H5-A',), ('C3H5-S',))
'hydrogen migration'
```

**Comment by avcopan** [comment]
The "substitutions" are no longer classified as such. We have made this class more strict, because it was giving too many false positives.

**Comment by lpratalimaffei** [comment]
thank you!! so I checked the InChI for C3H5-S in the data; we had stereo-expanded the spc dct so it is
AMChI=1/C3H5/c1-3-2/h1,3H,2H3/b3-1-
so I guess this is incompatible with C3H5-A? should I set stereo=False in generating the rxn object?

**Comment by avcopan** [comment]
Hey @lpratalimaffei -- yes, in general, it is best to classify first and then add stereo after. If you classify with stereo=True, then the classifier will include stereo parities in the comparison.

**Comment by avcopan** [comment]
I think this is resolved, so I will mark it as closed.

**Comment by avcopan** [comment]
I think this is resolved, so I will mark it as closed.

**Comment by lpratalimaffei** [comment]
Great, thank you. Probably when we introduced stereo I didn’t pay attention to this and kept the default option. I’ll switch to stereo=False in the next commit.

Da: avcopan ***@***.***>
Inviato: mercoledì 21 agosto 2024 15:18
A: Auto-Mech/mechanalyzer ***@***.***>
Cc: Luna Pratali Maffei ***@***.***>; Mention ***@***.***>
Oggetto: Re: [Auto-Mech/mechanalyzer] rxn class graphs "unclassified" vs previous classification as H migration or substitution (Issue #294)


Hey @lpratalimaffei<https://github.com/lpratalimaffei> -- yes, in general, it is best to classify first and then add stereo after. If you classify with stereo=True, then the classifier will include stereo parities in the comparison.
